# Rename this file to languages.toml to enable multilingual support
[en]
languageName = "English"
languagedirection = "ltr"
title = "Example Site"
weight = 1
[de]
languageName = "German"
languagedirection = "ltr"
title = "Beispiel Seite"
weight = 1