# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true
[[main]]
name = "Contact"
url = "/contact"
weight = 5
[main.params]
icon = "envelope-closed-svgrepo-com"

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/christophhaushofer/"

[social.params]
icon = "brand-github"
name = "envelope"
url = "mailto:your-email@example.com"
weight = 30

[[social]]
identifier = "linkedin"
name = "LinkedIn"
url = "https://www.linkedin.com/in/christophhaushofer/"

[social.params]
icon = "linkedin-svgrepo-com"
